apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  containers:
    - image: k8s.gcr.io/echoserver:1.4
      imagePullPolicy: IfNotPresent
      name: echoserver


